# Generated by Django 3.2.15 on 2022-09-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify_student', '0014_remove_softwaresecurephotoverification_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssoverification',
            name='identity_provider_type',
            field=models.CharField(choices=[('common.djangoapps.third_party_auth.models.OAuth2ProviderConfig', 'OAuth2 Provider'), ('common.djangoapps.third_party_auth.models.SAMLProviderConfig', 'SAML Provider'), ('common.djangoapps.third_party_auth.models.LTIProviderConfig', 'LTI Provider'), ('common.djangoapps.third_party_auth.models.CustomProviderConfig', 'Custom SSO')], default='common.djangoapps.third_party_auth.models.SAMLProviderConfig', help_text='Specifies which type of Identity Provider this verification originated from.', max_length=100),
        ),
    ]
