# Generated by Django 3.2.18 on 2023-05-15 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('third_party_auth', '0009_customproviderconfig'),
        ('third_party_auth', '0010_delete_historicalusersocialauth'),
    ]

    operations = [
    ]
